.dockerignore, Dockerfile, package.json, tsconfig.json
Prepare bot to deploy using docker on CapRover.
Add a multistage docker build that compiles the typescript project and then creates a docker image from the compiled source.
Running the bot in docker:
run ` docker build -t c0d3r .` to build the image
run `docker run --env DISCORD_TOKEN=token --env BOT_TOKEN=token c0d3r` to start a new container with the bot. The env variables are required.
Running the bot in CapRover:
Create the app on CapRover, add the two required env variables, deploy image.
=> Dockerize App

.github/workflows/main.yml
Create a GitHub action that automatically compiles the bot into a docker image and then deploys it to out CapRover server
=> Create workflow for CapRover deployment

config.ts, index.ts, src/Bot/events/index.ts, src/Bot/events/message.ts, src/Bot/index.ts
Adds an event listener that reacts to messages of new members joining in the welcome channel with a wave (👋)
=> Wave to new member messages in welcome channel

src/api/messages/index.ts, src/api/submissions/index.ts
Update the http status codes for successfully sent messages to 201 Created from 200 ok
=> Update message send status codes to 201

src/api/middlewares/errorHandler.ts
Changes
- Change status code for auth error to 401
- Change error to objects with a type and message, and an array of issues in case of zod error
=> Add types and messages to all error objects

package.json, src/Bot/index.ts, yarn.lock
- Upgrades Zod to the latest version
- Fix `SubmissionMessage` after the `sendSubmissionNotification` was changed in #13
=> Upgrade zod and fix types

src/Bot/commands.ts
Depends on #19 
This PR create the slashCommad for #15 and create the file that will store all the slash commands.
=> feat: create the slashCommand to get user info

package.json
This PR add [@discordjs/rest](https://www.npmjs.com/package/@discordjs/rest) that will be used to register the commands.
Example:
```ts
const rest = new REST({ version: "9" }).setToken(
process.env.DISCORD_TOKEN!
);
rest
.put(
Routes.applicationGuildCommands(
process.env.BOT_TOKEN!,
process.env.GUILD_ID!
),
{
body: commands,
}
)
.then(() => console.log("Successfully registered application commands."))
.catch(console.error);
```
=> build: add @discordjs/rest package

src/graphql.ts
Related to #15 
This PR add the [query](https://github.com/garageScript/c0d3-app/blob/d70ad8c47bbdbeef1f04808445197f90d2ec2fe6/graphql/resolvers.ts#L44) to retrieve the user `DiscordUsername` from.
It also create the `graphql.ts` file that'll stole all graphql requests
=> feat: add userInfo query

src/Bot/commands.ts
=> Revert "feat: create the slashCommand to get user info"

src/Bot/index.ts
=> feat(bot): add guild_messages and reactions intents

src/Bot/commands/commandsReplies.ts
Closes #29 
This PR uses the method [`interaction.deferReply()`](https://discordjs.guide/interactions/slash-commands.html#deferred-responses) to show an initial response and increase the timeout time to 15 minutes.
Initial response: 
When the request resolves:
=> fix(bot): interaction failed after 3 sec

src/Bot/commands/commands.ts, src/Bot/commands/commandsReplies.ts, src/Bot/commands/index.ts
Closes #31 
This PR shorten the [command](#15 ) to lookup a user username's on Discord to `/lookup username: <username>`
=> feat(bot): replace "/user find" with "/lookup"

.github/workflows/main.yml, app.ts, index.ts, package.json, src/Bot/commands/commands.ts, src/Bot/commands/commandsReplies.ts, src/Bot/commands/externals/gpt.ts, src/Bot/commands/index.ts, src/Bot/events/index.ts, src/Bot/index.ts, src/api/utils/asyncErrorHandler.ts, src/api/utils/validatorFactory.ts, src/graphql.ts, tsconfig.json
Added prettier commands to check formatting, and fix formatting to package json.
Used prettier to reformat existing files. Only formatting changes in this PR.
=> Fix file formatting

config.ts, example.env, src/Bot/index.ts, src/api/middlewares/authorized.ts
Renamed BOT_TOKEN to CLIENT_ID
Renamed BOT_ACCESS_TOKEN back to BOT_TOKEN
Add OPENAI_API_KEY in the example.env
Updated use to `config.discordToken` instead of `process.env.DISCORD_TOKEN`
=> Update env vars

README.md
Updated API request example in README.md to use the current api design.
=> Updated API request example in README.md

package.json, yarn.lock
- Added lint-staged dev dependency
- Added husky dev dependency
- Configured lint-staged to run eslint and prettier on staged files
- Configured husky to run lint-staged before commits
- Added "husky install" to prepare, this will install husky hooks when running `yarn install/yarn`
=> Add git pre commit hooks

Dockerfile
- Upgrade node from v17 to v18
- Add tini as the init process for docker
=> Upgrade node to v18 and add docker init process

package.json
Updated start command to build and run the built app instead of using ts-node
=> Update start command to remove ts-node

Dockerfile
Update dockerfile to install packages as root, and only run as node.
=> Update Dockerfile permissions
